-- Nombre, apellido e IP, donde la última conexión se dió de 221.XXX.XXX.XXX
SELECT
	first_name,
	last_name,
	last_connection
FROM
	users
WHERE
	last_connection LIKE '221.%';

-- Nombre, apellido y seguidores(followers) de todos a los que lo siguen más de 4600 personas
SELECT
	first_name,
	last_name,
	followers
FROM
	users
WHERE
	followers > 4600;

-----
SELECT
	*
FROM
	USERS;

SELECT
	COUNT(*) AS TOTAL_USERS,
	MIN(FOLLOWERS) AS MIN_FOLLOWERS,
	MAX(FOLLOWERS) AS MAX_FOLLOWERS,
	ROUND(AVG(FOLLOWERS)) AS AVG_FOLLOWERS,
	SUM(FOLLOWERS) / COUNT(*) AS AVG_MANUAL
FROM
	USERS;

-----
SELECT
	*
FROM
	USERS;

SELECT
	COUNT(*) AS TOTAL_USERS,
	MIN(FOLLOWERS) AS MIN_FOLLOWERS,
	MAX(FOLLOWERS) AS MAX_FOLLOWERS,
	ROUND(AVG(FOLLOWERS)) AS AVG_FOLLOWERS,
	SUM(FOLLOWERS) / COUNT(*) AS AVG_MANUAL
FROM
	USERS;

SELECT
	FIRST_NAME,
	LAST_NAME,
	FOLLOWERS
FROM
	USERS
WHERE
	FOLLOWERS = 4
	OR FOLLOWERS = 4999
SELECT
	COUNT(*),
	FOLLOWERS
FROM
	USERS
WHERE
	FOLLOWERS BETWEEN 4500 AND 4999
GROUP BY
	FOLLOWERS
ORDER BY
	FOLLOWERS DESC
--
SELECT
	*
FROM
	USERS
	--
SELECT
	COUNT(*) AS TOTAL,
	COUNTRY
FROM
	USERS
GROUP BY
	COUNTRY
HAVING
	COUNT(*) BETWEEN 1 AND 5
ORDER BY
	COUNT(*) DESC
--
SELECT DISTINCT COUNTRY FROM USERS;
--
SELECT
	COUNT(*),
	SUBSTRING(EMAIL, POSITION('@' IN EMAIL) + 1) AS DOMAIN
FROM
	USERS
GROUP BY
	SUBSTRING(EMAIL, POSITION('@' IN EMAIL) + 1)
HAVING
	COUNT(*) > 1
ORDER BY
	SUBSTRING(EMAIL, POSITION('@' IN EMAIL) + 1) ASC
--
SELECT
	*
FROM
	(
		SELECT
			COUNT(*) AS TOTAL,
			SUBSTRING(EMAIL, POSITION('@' IN EMAIL) + 1) AS DOMAIN,
			'Tomás' AS NAME,
			20 AS AGE
		FROM
			USERS
		GROUP BY
			SUBSTRING(EMAIL, POSITION('@' IN EMAIL) + 1)
		HAVING
			COUNT(*) > 1
		ORDER BY
			SUBSTRING(EMAIL, POSITION('@' IN EMAIL) + 1) ASC
	) AS EMAIL_DOMAINS;